# -*- coding: utf-8 -*-
"""dataset51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByzjYHt2YgOxiu-7pWKLRXGzjcvmi5yH
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv("OnlineNewsPopularity.csv")

data.isnull().sum

data.head()

data.columns = data.columns.str.strip()

X = data[['n_tokens_title', 'n_tokens_content']]

X.head()

y = data['shares']

y.head()

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=0)

X_train.shape

X_test.shape

DT=DecisionTreeClassifier()

DT.fit(X_train, y_train)

y_predictions =DT.predict(X_test)

accuracy = accuracy_score(y_test, y_predictions)
print("Accuracy:", accuracy)